server:
  port: 8082

spring:
  application:
    name: dubbo-provider-b

service-b:
  datasource:
    master:
      url: jdbc:mysql://localhost:3326/db_0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      configuration:
        cache-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true
        use-local-session-state: true
        rewrite-batched-statements: true
        cache-result-set-metadata: true
        cache-server-configuration: true
        elide-set-auto-commits: true
        maintain-time-stats: false

dubbo:
  scan:
    base-packages: com.carl.geek.service.b.service
  protocol:
    name: dubbo
    port: 12346
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
  application:
    qosEnable: true
    qosPort: 22222
    qosAcceptForeignIp: true
    qos-enable-compatible: true
    qos-host-compatible: localhost
    qos-port-compatible: 22222
    qos-accept-foreign-ip-compatible: true
    qos-host: localhost