package com.carl.geek.service.a.model;

import java.math.BigDecimal;
import java.util.Date;

public abstract class UserAccount_Field extends BaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account. id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.user_id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private String userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.type
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.balance
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private BigDecimal balance;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.update_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account.create_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account. id
     *
     * @return the value of user_account. id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account. id
     *
     * @param id the value for user_account. id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.user_id
     *
     * @return the value of user_account.user_id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.user_id
     *
     * @param userId the value for user_account.user_id
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.type
     *
     * @return the value of user_account.type
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.type
     *
     * @param type the value for user_account.type
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.balance
     *
     * @return the value of user_account.balance
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public BigDecimal getBalance() {
        return balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.balance
     *
     * @param balance the value for user_account.balance
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setBalance(BigDecimal balance) {
        this.balance = balance;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.update_time
     *
     * @return the value of user_account.update_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.update_time
     *
     * @param updateTime the value for user_account.update_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account.create_time
     *
     * @return the value of user_account.create_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account.create_time
     *
     * @param createTime the value for user_account.create_time
     *
     * @mbg.generated Thu Jul 08 16:58:38 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}