package com.carl.geek.service.b.model;

import java.math.BigDecimal;
import java.util.Date;

public abstract class UserAccountFreeze_Field extends BaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_freeze.id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_freeze.user_account_id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    private Integer userAccountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_freeze.amount
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_freeze.create_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_account_freeze.update_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_freeze.id
     *
     * @return the value of user_account_freeze.id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_freeze.id
     *
     * @param id the value for user_account_freeze.id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_freeze.user_account_id
     *
     * @return the value of user_account_freeze.user_account_id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public Integer getUserAccountId() {
        return userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_freeze.user_account_id
     *
     * @param userAccountId the value for user_account_freeze.user_account_id
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public void setUserAccountId(Integer userAccountId) {
        this.userAccountId = userAccountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_freeze.amount
     *
     * @return the value of user_account_freeze.amount
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_freeze.amount
     *
     * @param amount the value for user_account_freeze.amount
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_freeze.create_time
     *
     * @return the value of user_account_freeze.create_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_freeze.create_time
     *
     * @param createTime the value for user_account_freeze.create_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_account_freeze.update_time
     *
     * @return the value of user_account_freeze.update_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_account_freeze.update_time
     *
     * @param updateTime the value for user_account_freeze.update_time
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}