server:
  port: 8083


dubbo:
  scan:
    base-packages: com.carl.geek.service.c.service
  registry:
    address: zookeeper://localhost:2181
  metadata-report:
    address: zookeeper://localhost:2181
