package com.carl.geek.service.b.dao;

import com.carl.geek.service.b.model.UserAccountFreeze;

public interface UserAccountFreezeMapper  {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    int insert(UserAccountFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    int insertSelective(UserAccountFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    UserAccountFreeze selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    int updateByPrimaryKeySelective(UserAccountFreeze record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_account_freeze
     *
     * @mbg.generated Thu Sep 02 16:45:51 CST 2021
     */
    int updateByPrimaryKey(UserAccountFreeze record);
}