server:
  port: 8081

service-a:
  datasource:
    master:
      url: jdbc:mysql://localhost:3316/db_0?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
      username: root
      password:
      driver-class-name: com.mysql.cj.jdbc.Driver
      configuration:
        cache-prep-stmts: true
        prep-stmt-cache-size: 250
        prep-stmt-cache-sql-limit: 2048
        use-server-prep-stmts: true
        use-local-session-state: true
        rewrite-batched-statements: true
        cache-result-set-metadata: true
        cache-server-configuration: true
        elide-set-auto-commits: true
        maintain-time-stats: false