package com.carl.geek.service.c.model;

import java.math.BigDecimal;
import java.util.Date;

public abstract class TransferLog_Field extends BaseModel<Integer> {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.from_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private String fromUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.to_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private String toUserId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.amount
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private BigDecimal amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.status
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private Byte status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.update_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column transfer_log.create_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.id
     *
     * @return the value of transfer_log.id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.id
     *
     * @param id the value for transfer_log.id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.from_user_id
     *
     * @return the value of transfer_log.from_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public String getFromUserId() {
        return fromUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.from_user_id
     *
     * @param fromUserId the value for transfer_log.from_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setFromUserId(String fromUserId) {
        this.fromUserId = fromUserId == null ? null : fromUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.to_user_id
     *
     * @return the value of transfer_log.to_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public String getToUserId() {
        return toUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.to_user_id
     *
     * @param toUserId the value for transfer_log.to_user_id
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setToUserId(String toUserId) {
        this.toUserId = toUserId == null ? null : toUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.amount
     *
     * @return the value of transfer_log.amount
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.amount
     *
     * @param amount the value for transfer_log.amount
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.status
     *
     * @return the value of transfer_log.status
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.status
     *
     * @param status the value for transfer_log.status
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.update_time
     *
     * @return the value of transfer_log.update_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.update_time
     *
     * @param updateTime the value for transfer_log.update_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column transfer_log.create_time
     *
     * @return the value of transfer_log.create_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column transfer_log.create_time
     *
     * @param createTime the value for transfer_log.create_time
     *
     * @mbg.generated Fri Sep 03 16:01:27 CST 2021
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}