package com.carl.geek.service.c.dao;

import com.carl.geek.service.c.model.TransferLog;

public interface TransferLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    int insert(TransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    int insertSelective(TransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    TransferLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    int updateByPrimaryKeySelective(TransferLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table transfer_log
     *
     * @mbg.generated Fri Sep 03 15:55:07 CST 2021
     */
    int updateByPrimaryKey(TransferLog record);
}